---
- name: Fail if variable change_fact is true
  hosts: all
  gather_facts: false
  become: false
  tasks:
    - name: Fail if variable change_fact is true
      ansible.builtin.fail:
        msg: change_fact is true
      when: change_fact is defined and change_fact == true

...
