- hosts: localhost
  gather_facts: yes
  remote_user: ansible
  become: true
  become_method: sudo
  collections:
    - community.general
  vars:
    - ansible_python_interpreter=/usr/bin/python3

  roles:
    - rhel8STIG
